# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='FosUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=180)),
                ('username_canonical', models.CharField(max_length=180, unique=True)),
                ('email', models.CharField(max_length=180)),
                ('email_canonical', models.CharField(max_length=180, unique=True)),
                ('enabled', models.IntegerField()),
                ('salt', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('locked', models.IntegerField()),
                ('expired', models.IntegerField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('password_requested_at', models.DateTimeField(blank=True, null=True)),
                ('roles', models.TextField()),
                ('credentials_expired', models.IntegerField()),
                ('credentials_expire_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fos_user',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('order_date', models.DateTimeField()),
                ('status', models.CharField(max_length=32)),
                ('product_id', models.IntegerField()),
                ('size', models.CharField(max_length=32)),
                ('img', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=32)),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('description', models.TextField()),
                ('a_img', models.ImageField(upload_to='images')),
                ('b_img', models.CharField(max_length=45)),
                ('c_img', models.CharField(max_length=45)),
                ('cat_id', models.IntegerField()),
                ('parent_id', models.IntegerField()),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Brand')),
            ],
            options={
                'ordering': ('id',),
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Productsize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
            ],
            options={
                'db_table': 'productsize',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_id', models.IntegerField()),
                ('size', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'size',
            },
        ),
        migrations.AddField(
            model_name='productsize',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Size'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(through='app.Productsize', to='app.Size'),
        ),
    ]
